const TEACHER = {
    CREATE: "TEACHER_CREATE_REQUEST",
    CREATE_SUCCESS: "TEACHER_CREATE_SUCCESS",
    CREATE_FAIL: "TEACHER_CREATE_FAIL",

    LOAD: 'TEACHER_LOAD_REQUEST',
    LOAD_SUCCESS: 'TEACHER_LOAD_SUCCESS',
    LOAD_FAIL: 'TEACHER_LOAD_FAIL',

    DELETE: "TEACHER_DELETE_REQUEST",
    DELETE_SUCCESS: "TEACHER_DELETE_SUCCESS",
    DELETE_FAIL: "TEACHER_DELETE_FAIL",

    EDIT: "TEACHER_EDIT_REQUEST",
    EDIT_SUCCESS: "TEACHER_EDIT_SUCCESS",
    EDIT_FAIL: "TEACHER_EDIT_FAIL"
}

export default TEACHER;