const USER = {
    CREATE: "USER_CREATE_REQUEST",
    CREATE_SUCCESS: "USER_CREATE_SUCCESS",
    CREATE_FAIL: "USER_CREATE_FAIL",

    LOAD: 'USER_LOAD_REQUEST',
    LOAD_SUCCESS: 'USER_LOAD_SUCCESS',
    LOAD_FAIL: 'USER_LOAD_FAIL',

    DELETE: "USER_DELETE_REQUEST",
    DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    DELETE_FAIL: "USER_DELETE_FAIL",

    EDIT: "USER_EDIT_REQUEST",
    EDIT_SUCCESS: "USER_EDIT_SUCCESS",
    EDIT_FAIL: "USER_EDIT_FAIL"
}

export default USER;